version: "3.8"

services:
  paymybuddy-db:
    image: localhost:5000/mysql:v8
    container_name: paymybuddy-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  paymybuddy-backend:
    image: localhost:5000/paymybuddy-backend:v1
    container_name: paymybuddy-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - paymybuddy-db

volumes:
  db_data:
